/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * VistaAcerca.java
 *
 * Created on 22/04/2011, 12:11:53 PM
 */

package presentacion;

/**
 *
 * @author oaromerov
 */
public class VistaAcerca extends javax.swing.JDialog {

    /** Creates new form VistaAcerca */
    public VistaAcerca() {
        this.setModal(true);
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
      // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
      private void initComponents() {

            jLabel1 = new javax.swing.JLabel();
            jLabel2 = new javax.swing.JLabel();
            jLabel3 = new javax.swing.JLabel();
            jLabel4 = new javax.swing.JLabel();

            setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
            setAlwaysOnTop(true);
            setResizable(false);
            getContentPane().setLayout(null);

            jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
            jLabel1.setForeground(java.awt.Color.red);
            jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            jLabel1.setText("Mis Caminos");
            getContentPane().add(jLabel1);
            jLabel1.setBounds(30, 30, 320, 40);

            jLabel2.setText("Idea 2011-2020");
            getContentPane().add(jLabel2);
            jLabel2.setBounds(30, 140, 290, 20);

            jLabel3.setText("Programa de demostración");
            getContentPane().add(jLabel3);
            jLabel3.setBounds(30, 80, 290, 20);

            jLabel4.setText("Universidad Distrital Francisco Jose de Caldas");
            getContentPane().add(jLabel4);
            jLabel4.setBounds(30, 110, 330, 20);

            pack();
      }// </editor-fold>//GEN-END:initComponents
  

      // Variables declaration - do not modify//GEN-BEGIN:variables
      private javax.swing.JLabel jLabel1;
      private javax.swing.JLabel jLabel2;
      private javax.swing.JLabel jLabel3;
      private javax.swing.JLabel jLabel4;
      // End of variables declaration//GEN-END:variables

}
